# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='member_level',
            field=models.PositiveIntegerField(default=1, verbose_name='\u4f1a\u5458\u7ea7\u522b'),
        ),
    ]
