# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-14 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_profile_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecoupon',
            name='can_sale',
            field=models.BooleanField(default=False, verbose_name='\u53ef\u51fa\u552e'),
        ),
    ]
